version: "3.7"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: glyphdb
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - "54321:5432"
    volumes:
      - glyphdb_pgdb:/var/lib/postgresql/glyphdb_data

volumes:
  glyphdb_pgdb:
